### ISSUE TITLE
Expose internal methods / Low-level wrapper?

### ISSUE THREAD

**Issue by FaberSanZ** [amerkoleci/Vortice.Vulkan#1]
Hi,

Any news here?

I would like to know if the library will be handwritten or generated by the vk.xml, I would like to help if it is handwritten and based on structures

**Comment by FaberSanZ** [comment]
Hi @amerkoleci, 

Great you are using SharGen for links, I like the idea of ​​putting (SType and Next) in public as it helps to pass examples of C.
 
I'll be on the lookout.

**Comment by amerkoleci** [comment]
You can grab beta nuget packages and test if you want

**Comment by FaberSanZ** [comment]
Hi ,
I already tried the library and it's great, thanks

https://github.com/FaberSanZ/Zeckoxe-Engine

**Comment by amerkoleci** [comment]
Just added lot of helpers and usage of readonly span for performance, try it and report any issues
