### ISSUE TITLE
System.TypeLoadException when using vkDebugUtilsMessengerCallbackEXT

### ISSUE THREAD

**Issue by Ash39** [amerkoleci/Vortice.Vulkan#12]
Could not load type 'Vortice.Vulkan.vkDebugUtilsMessengerCallbackEXT' from assembly 'Vortice.Vulkan, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'.'
Error is there from 1.3.0 -> current version

**Comment by amerkoleci** [comment]
Are you targeting net5 or lower? With net5 it should work

**Comment by Ash39** [comment]
yes net5

**Comment by amerkoleci** [comment]
Its only netstandard2.0 feature, in net5 you just use delegate (function pointers) see here https://github.com/amerkoleci/Vortice.Vulkan/blob/main/src/samples/01-ClearScreen/GraphicsDevice.cs#L90

**Comment by Ash39** [comment]
Thanks I missed that
