### ISSUE TITLE
How to set VkDebugUtilsMessengerCreateInfoEXT.pfnUserCallback in netstandard2.0

### ISSUE THREAD

**Issue by manuelxmarquez** [amerkoleci/Vortice.Vulkan#14]
How do you set `VkDebugUtilsMessengerCreateInfoEXT.pfnUserCallback`?

I was previously using 1.3.4 and updated to 1.3.16. I was using `Marshal.GetFunctionPointerForDelegate()` on a delegate of type `vkDebugUtilsMessengerCallbackEXT` but that is not possible anymore.

If I copy the new struct into my code it won't event compile
```
	[StructLayout(LayoutKind.Sequential)]
	public partial struct VkDebugUtilsMessengerCreateInfoEXT
	{
		public VkStructureType sType;
		public unsafe void* pNext;
		public VkDebugUtilsMessengerCreateFlagsEXT flags;
		public VkDebugUtilsMessageSeverityFlagsEXT messageSeverity;
		public VkDebugUtilsMessageTypeFlagsEXT messageType;
		#if NETSTANDARD2_0
		public unsafe delegate* unmanaged[Stdcall]<VkDebugUtilsMessageSeverityFlagsEXT, VkDebugUtilsMessageTypeFlagsEXT, VkDebugUtilsMessengerCallbackDataEXT*, void*, uint> pfnUserCallback;
		#else
		public unsafe delegate* unmanaged<VkDebugUtilsMessageSeverityFlagsEXT, VkDebugUtilsMessageTypeFlagsEXT, VkDebugUtilsMessengerCallbackDataEXT*, void*, uint> pfnUserCallback;
		#endif
		public unsafe void* pUserData;
	}
```
error CS8370: Feature 'function pointers' is not available in C# 7.3. Please use language version 9.0 or greater.

My project target
`<TargetFrameworks>netstandard2.0</TargetFrameworks>`

which finally gets referenced in a project with
`<TargetFrameworks>net472;netcoreapp3.1</TargetFrameworks>`

BTW, thanks for adding netstandard2.0 back in. I was having trouble updating to net5 since all my dependencies haven't caught up yet.

**Comment by amerkoleci** [comment]
Can you try to upgrade the language version to 9.0 and see if it works?

**Comment by amerkoleci** [comment]
If i have to support opengl and openal i would go with the same route as this vulkan bindings, parse the header file and generate the api, maybe would use xml specs for enum creation

**Comment by amerkoleci** [comment]
You can use those bindings https://github.com/WaveEngine/OpenGL.NET
