### ISSUE TITLE
VkTransformMatrixKHR only has 3 floats

### ISSUE THREAD

**Issue by Jorgemagic** [amerkoleci/Vortice.Vulkan#2]
**VkTransformMatrixKHR** is a Matrix3x4 [Vulkan specification](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkTransformMatrixKHR.html) so it should have 12 floats.

```
namespace Vortice.Vulkan
{
    public struct VkTransformMatrixKHR
    {
        public float matrix_0;
        public float matrix_1;
        public float matrix_2;
    }
}
```

**Comment by amerkoleci** [comment]
Thanks for spotting this, fixes with last commit, I updated to vulkan 1.2.140 headers as well.
