### ISSUE TITLE
How to compile/ initial set up error

### ISSUE THREAD

**Issue by RrayAgent** [amerkoleci/Vortice.Vulkan#29]
When trying to build/set up this Vulkan I get: error MSB4237: The SDK resolver
 type "DotNetMSBuildSdkResolver" failed to load. The type initializer for 'Microsoft.DotNet.MSBuildSdkResolver.VSSettin
gs' threw an exception. And I don't what to do.

**Comment by amerkoleci** [comment]
This isn't an issue related to vortice vulkan, but probably with your development environment/settings

**Comment by RrayAgent** [comment]
So then how do I fix it?

**Comment by amerkoleci** [comment]
Google it man!

**Comment by RrayAgent** [comment]
thanks

**Comment by amerkoleci** [comment]
I quickly Google and found this: https://github.com/dotnet/msbuild/issues/4227
