### ISSUE TITLE
vkBeginCommandBuffer flags parameter ignored in helper function

### ISSUE THREAD

**Issue by ItsNovaHere** [amerkoleci/Vortice.Vulkan#32]
vkBeginCommandBuffer takes in flags, but then just sets OneTimeSubmit anyway?

https://github.com/amerkoleci/Vortice.Vulkan/blob/620d2ecf0508d9cf61da36ea64b2b60650508023/src/Vortice.Vulkan/Vulkan.cs#L459-L468

**Comment by amerkoleci** [comment]
Fixed, thanks!
