### ISSUE TITLE
VMA with Silk.NET keeps crashing 

### ISSUE THREAD

**Issue by citruslee** [amerkoleci/Vortice.Vulkan#46]
Hello. I am trying to use your VMA and shaderc bindings, but I keep getting my app crashing. I use Silk.NET as vulkan api wrapper, and unfortunately right now I am already super invested in it to make the change. I am trying to just create an allocator and it keeps crashing on me.

In Silk.NET <VkObject>.Handle is actually the real value of the object, as it would be in C. I am sending these to vmaCreateAllocator, and it keeps on crashing in "OnDllImport" callback. It gets here 

`if (libraryName.Equals(LibName) && TryResolveVMA(assembly, searchPath, out nativeLibrary))
        {
            return nativeLibrary;
        }`
        
All I do on my side is this:

`VmaAllocatorCreateInfo allocatorCreateInfo;
	    allocatorCreateInfo.vulkanApiVersion = VkVersion.Version_1_2;
	    allocatorCreateInfo.physicalDevice = pdev.Handle;
	    allocatorCreateInfo.device = dev.Handle;
	    allocatorCreateInfo.instance = instance.Handle;
	    VmaAllocator allocator;
	    vmaCreateAllocator(&allocatorCreateInfo, &allocator).CheckResult();`
	    
and respectively before (successfully!!!) initializing vulkan, which runs without any validation errors. I am quite helpless with what might be going on. This is on Linux operating system, more specifically on Pop_OS!

**Comment by amerkoleci** [comment]
Do you have an arm64 or x64 linux?

**Comment by amerkoleci** [comment]
> I can't make the source available but I am more than willing to show you on a call what it does

As you can see, this is spare time project, if you can please debug the issue and submit PR in case.

Thankss!

**Comment by amerkoleci** [comment]
Hi,
Thanks for feedback, this has been handled by the library, please update to `1.4.3` and assign the pVulkanFunctions with your own functions.

Tell me if works.
Thanks!

**Comment by amerkoleci** [comment]
> it looks like it works. Thank you very much for the fix! <3 Have a nice day!

Glad it works, have a nice day as well!
