### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by taumuon** [amerkoleci/Vortice.Vulkan#5]
Hi,
I was unable to get Android Vulkan code working with Vortice.Vulkan. However, if I comment out the dlerror() call in the UnixLoader.LoadNativeLibrary method then it works without problem (see the commit in https://github.com/taumuon/Vortice.Vulkan ).

Is there a reason this call is there? Can it be fixed (I have forked Vortice.Vulkan to make this change but I'd prefer to reference the official version on Nuget).

The sample code is here: https://github.com/taumuon/TexturedCube-Vortice

Thanks,

Gary

**Comment by amerkoleci** [comment]
Will fix it Monday morning, thanks for reporting

**Comment by amerkoleci** [comment]
Fixed now, you can use the **1.2.152.1** version.

**Comment by taumuon** [comment]
> 
> 
> Fixed now, you can use the **1.2.152.1** version.

That's great, much appreciated, thanks for the fast turnaround!
