### ISSUE TITLE
Triangle sample - instable colors

### ISSUE THREAD

**Issue by isolin** [amerkoleci/Vortice.Vulkan#50]
When I run the Sample 02 with a triangle, I always get a different result. Sometimes three colors (RGB) are present, but mostly there is something missing. This changes each time I run the example without any code editing. Just a repeated `dotnet run`. I have the feeling that blue is always present, but red and green are often substituted by black. Any what could be the cause or how to search for it?

The correct one:
![image](https://github.com/user-attachments/assets/0ac1e5ea-094f-47b1-925c-55ab7312dab9)

Wrong results, randomly obtained:
![image](https://github.com/user-attachments/assets/31732a6e-3477-45f0-a3ba-d9b696695e88)
![image](https://github.com/user-attachments/assets/450267ae-e672-475d-b465-ab8aef8fe579)
![image](https://github.com/user-attachments/assets/3d160459-173d-4100-8f7f-67983b82a5e2)

**Comment by amerkoleci** [comment]
Not sure whats wrong here, never happened to me actually

**Comment by isolin** [comment]
In the cases when it messes up, there is also alpha wrong. I assume it will be some sort of a memory issue. Positions are always correct, though. And surprisingly, having a constant blue always yields a correct result.

**Comment by isolin** [comment]
A friend of mine tested it on Win, saying it looks ok. I would like to trace if this can be a driver bug or code bug.

- Is there a specific Linux pipeline in Vortice or is all the code platform independent? 
- Do you have the option to test under Linux?
