### ISSUE TITLE
Any plans for add Shaderc?

### ISSUE THREAD

**Issue by FaberSanZ** [amerkoleci/Vortice.Vulkan#7]
Hi, 

As Vortice.Windows has Dxc, I think this is the best place for [Shaderc ](https://github.com/google/shaderc),
 I can send PR.

[Shaderc-C#](https://github.com/FaberSanZ/Shaderc.NET)

Cheers,
Faber

**Comment by amerkoleci** [comment]
https://www.nuget.org/packages/Vortice.ShaderCompiler just landed, feel free to open any issues or improvements.
