### ISSUE TITLE
vkCmdSetBlendConstants: wrong argument type

### ISSUE THREAD

**Issue by konstantinegorov** [amerkoleci/Vortice.Vulkan#8]
The "_blendConstants_" argument of the "_vkCmdSetBlendConstants_" command must be a pointer to _float_.

current command signature:
`void vkCmdSetBlendConstants(VkCommandBuffer commandBuffer, float blendConstants);`

valid command signature:
`void vkCmdSetBlendConstants(VkCommandBuffer commandBuffer, float* blendConstants);`

**Comment by amerkoleci** [comment]
Thanks for reporting this!
Version 1.2.166.4 resolves this.
